//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EgitimUygulamaWebProjesi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kullanicilar
    {
        public Kullanicilar()
        {
            this.Odevler = new HashSet<Odevler>();
            this.OdevTeslimleri = new HashSet<OdevTeslimleri>();
            this.PdfCalismalar = new HashSet<PdfCalismalar>();
        }
    
        public int KullaniciId { get; set; }
        public string AdSoyad { get; set; }
        public string Eposta { get; set; }
        public string Sifre { get; set; }
        public string Rol { get; set; }
    
        public virtual ICollection<Odevler> Odevler { get; set; }
        public virtual ICollection<OdevTeslimleri> OdevTeslimleri { get; set; }
        public virtual ICollection<PdfCalismalar> PdfCalismalar { get; set; }
    }
}
