//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EgitimUygulamaWebProjesi.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EgitimSitesiProjeTasarimiEntities1 : DbContext
    {
        public EgitimSitesiProjeTasarimiEntities1()
            : base("name=EgitimSitesiProjeTasarimiEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Kullanicilar> Kullanicilar { get; set; }
        public DbSet<Odevler> Odevler { get; set; }
        public DbSet<OdevTeslimleri> OdevTeslimleri { get; set; }
        public DbSet<PdfCalismalar> PdfCalismalar { get; set; }
    }
}
