//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EgitimUygulamaWebProjesi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OdevTeslimleri
    {
        public int TeslimId { get; set; }
        public Nullable<int> OdevId { get; set; }
        public Nullable<int> OgrenciId { get; set; }
        public string TeslimDosyaYolu { get; set; }
        public Nullable<System.DateTime> TeslimTarihi { get; set; }
        public Nullable<int> Puan { get; set; }
    
        public virtual Kullanicilar Kullanicilar { get; set; }
        public virtual Odevler Odevler { get; set; }
    }
}
