//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EgitimUygulamaWebProjesi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Odevler
    {
        public Odevler()
        {
            this.OdevTeslimleri = new HashSet<OdevTeslimleri>();
        }
    
        public int OdevId { get; set; }
        public string Baslik { get; set; }
        public string Aciklama { get; set; }
        public string DosyaYolu { get; set; }
        public Nullable<System.DateTime> YuklenmeTarihi { get; set; }
        public Nullable<int> OgretmenId { get; set; }
    
        public virtual Kullanicilar Kullanicilar { get; set; }
        public virtual ICollection<OdevTeslimleri> OdevTeslimleri { get; set; }
    }
}
